- name: checking data types
  hosts: localhost
  vars:
    NAME: ManojKumar  # key value
    Skills:    # Skills is a list type 
    - Devops
    - Shell 
    - Ansible 
    - Linux 
    Experience:  #Experiece is map type it contains key value pairs
      Devops: 10
      AWS: 6
      Docker: 4 
    Trainer: true  # boolean 
  tasks:
    - name: printing key value pair
      ansible.builtin.debug:
        msg: "{{NAME}} "
    - name: printing list data type
      ansible.builtin.debug:
        msg: "{{Skills}}"
    - name: printing map data type 
      ansible.builtin.debug:
        msg: "{{Experience}}"
    - name: printing boolean
      ansible.builtin.debug:
        msg: "{{Trainer}}"
