- name: installing and uninstalling through loops
  hosts: loclahost
  become: yes
  tasks:
  - name: installing and uninstalling packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"  # item is a default keyword 
    loop:
    - {name: git, state: present}
    - {name: mysql, state: absent}
    - {name: nginx, state: absent}

