- name: Task1 and Play1
  hosts: web
  tasks:
  - name: Message is from task 1 and play 1
    ansible.builtin.debug:
      msg: "Hi I am from play 1"

- name: Task2 and Play2
  hosts: web
  tasks:
  - name: Message is from Task2 and Play2
    ansible.builtin.debug:
      msg: :Hi I am from play 2"