- name: practicing condition in ansible
  hosts: localhost 
  become: yes 
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: yes 
  - name: printing user variable
    ansible.builtin.debug:
      msg: "output is {{user}}"
  - name: printing exit status
    ansible.builtin.debug:
      msg: "{{user.rc}}"
  - name: creating user 
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0 