- name: Printing Manoj Details
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: This is about me
    ansible.builtin.debug:
      msg: "Hi My name is {{Name}} I completed my Btech in the stream of {{Stream}} from {{College}}"