- name: creating user
  hosts: localhost
  become: yes 
  tasks:
  - name: Checking user
    ansible.builtin.command: id roboshop
    register: user 
    ignore_errors: yes 
  - name: printing user value 
    ansible.builtin.debug:
      msg: "{{user}}"
  - name: printing exit status
    ansible.builtin.debug:
      msg: "{{user.rc}}"
