- name: creating user
  hosts: loclahost
  tasks:
  - name: Checking user
    ansible.builtin.command: id roboshop
    register: user 
    ignore_errors: yes 
  - name: printing user value 
    ansible.builtin.debug:
      msg: "{{user}}"
