- name: About manoj kumar
  hosts: localhost 
  vars:
    Name: Manoj kumar
    Degree: Btech
    Hobbies: Watching Movies
    Company: Prodapt
  tasks:
  - name: Printing Manoj Details
    ansible.builtin.debug:
      msg: "Hi My name is {{Name}} I completed my {{Degree}} My Hobbies are {{Hobbies}} My company name was {{Company}}"
