- name: About manoj 
  hosts: localhost 
  vars:
    Name: Manoj Kumar
    Degree: Btech
    College: GVPCOE
    Comapny: Prodapt
  tasks:
  - name: printing manoj information
    ansible.builtin.debug:
      msg: "Hi My name is {{Name}} I completed my {{Degree}} My college name is {{College}} I worked in {{Company}}"