- name: Manoj Details
  hosts: loclahost 
  vars:
    degree: Diploma
  tasks:
  - name: Printing Manoj Details
    vars:
      Name: Manoj kumar
      Degree: Btech
    ansible.builtin.debug:
      msg: "Hi My name is {{Name}} I completed my {{Degree}}"