- name: installing packages
  hosts: loclahost 
  become: yes 
  tasks:
  - installing package one by one 
    ansible.builtin.package:
      name: "{{item}}"
      state: present 
    loop:
    - git 
    - ansible 
    - nginx 