- name: practicing condition in ansible
  hosts: localhost 
  become: yes 
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: user
    ignore-errors: yes 
  - name: printing user variable
    ansible.builtin.debug:
      msg: "output is {{user}}"