- name: installing packages
  hosts: localhost 
  become: yes 
  tasks:
  - name: installing package one by one 
    ansible.builtin.package:
      name: "{{item}}"
      state: present 
    loop:
    - git 
    - ansible 
    - nginx 