- name: USERNAME and PASSWORD
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Enter Your USERNAME
    private: false 
  - name: PASSWORD
    prompt: Enter Your PASSWORd
    private: true 
  tasks:
  - name: Displaying your username and password
    ansible.builtin.debug:
      msg: "This is your {{USERNAME}} and {{PASSWORD}}"